import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillHeart } from 'react-icons/ai';
import Image from 'next/image';
import cv from '../public/cv.png';
import a from '../public/a.png';
import d from '../public/d.png';
import f from '../public/f.png';
import ph1 from '../public/ph1.jpg';
import ph2 from '../public/ph2.jpg';
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Johannas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white'>
        
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between sticky'>
            <h1 className='text-xl dark:text-white'>Johanna Fogel</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
                </li>
              <li>
                <a className='bg-gradient-to-r from-teal-600 to-teal-900 text-white px-4 py-2 rounded-md ml-8 cursor-pointer' href='#'>Button</a>
                </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Welcome to my portfolio</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Frontend developer and UX/UI.</h3>
            <p className='text-md py-5 leading-6 text-gray-800 md:text-xl mx-auto dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis risus, iaculis pellentesque accumsan ut, ultrices tempor urna. 
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-teal-900 '>
            <AiFillLinkedin />
            <AiFillGithub />
            <AiFillHeart />
          </div>

          <div className='relative mx-auto bg-gradient-to-t from-teal-700 w-90 h-90 rounded-full mt-20 flex justify-center lg:object-scale-down'>
            <Image src={cv} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section className='text-center lg:mt-6'>
          <div>
            <h3 className='text-3xl pt-5'>Lorem Ipsum Skills</h3>
            <p className='text-md py-4 leading-6 text-gray-800 dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse <span className='text-teal-600'>aliquet</span> sagittis est quis fermentum.
            Nullam accumsan <span className='text-teal-600'>hendrerit</span> malesuada. Maecenas tempus mi convallis nisl accumsan aliquet ut eget augue.
            </p>
          </div>

          <div className='lg:flex gap-10 text-center flex justify-center'>
            <div className='shadow-lg p-10 rounded xl my-10 dark:bg-gray-600'>
              <div className='mx-auto flex justify-center'>
                <Image src={d} width={300} height={300} />
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 1</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>

            <div className='shadow-lg p-10 rounded xl my-10 dark:bg-gray-600'>
              <div className='mx-auto flex justify-center'>
                <Image src={f} width={300} height={300}/>
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 2</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>
            <div className='shadow-lg p-10 rounded xl my-10 dark:bg-gray-600'>
              <div className='mx-auto flex justify-center'>
                <Image src={a} width={300} height={300}/>
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 3</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>
          </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-6 text-gray-800 dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse <span className='text-teal-600'>aliquet</span> sagittis est quis fermentum.
            Nullam accumsan <span className='text-teal-600'>hendrerit</span> malesuada. Maecenas tempus mi convallis nisl accumsan aliquet ut eget augue.
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basis-1/3 flex-1'>
              <Image src={ph1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={ph2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={ph1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={ph2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={ph1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={ph2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>

          </div>
        </section>

      </main>
    </div>
  )
}
