import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Link from 'next/link';

import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillHeart } from 'react-icons/ai';

import cv from '../public/cv.png';
import Fisher from '../public/Fisher.png';
import SneakerHeadz from '../public/SneakerHeadz.png';
import Sl from '../public/Sl.png';
import Login from '../public/login.png';
import Port from '../public/port.png';
import Port2 from '../public/port-2.png';

import a from '../public/A.png';
import d from '../public/D.png';
import f from '../public/F.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Johannas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white'>
        
        <nav className='py-10 mb-12 flex justify-between sticky top-0 z-10'>
            <h1 className='text-teal-600 text-xl font-bold dark:text-white'>Johanna Fogel</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
                </li>
              <li>
                <Link className='bg-gradient-to-r from-teal-600 to-teal-900 text-white px-4 py-2 rounded-md ml-8 cursor-pointer' href='/contact'>Say Hello!</Link>
                </li>
            </ul>
          </nav>

        <section className='min-h-screen relative'>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Welcome to my portfolio</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Frontend developer and UX/UI.</h3>
            <p className='text-md py-5 leading-6 text-gray-800 md:text-xl mx-auto dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis risus, iaculis pellentesque accumsan ut, ultrices tempor urna. 
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-teal-900 '>
            <Link href="https://www.linkedin.com/in/johanna-fogel-47209670/"><AiFillLinkedin /></Link>
            <Link href="https://github.com/Vitoleander"><AiFillGithub /></Link>
            <Link href=""><AiFillHeart /></Link>
          </div>

          <div className='relative mx-auto bg-gradient-to-t from-teal-700 w-90 h-90 rounded-full mt-20 flex justify-center lg:object-scale-down'>
            <Image src={cv} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section className='text-center lg:mt-6'>
          <div>
            <h3 className='text-3xl pt-5'>Lorem Ipsum Skills</h3>
            <p className='text-md py-4 leading-6 text-gray-800 dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse <span className='text-teal-600'>aliquet</span> sagittis est quis fermentum.
            Nullam accumsan <span className='text-teal-600'>hendrerit</span> malesuada. Maecenas tempus mi convallis nisl accumsan aliquet ut eget augue.
            </p>
          </div>

          <div className='lg:flex gap-10 text-center justify-center'>
            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={d} width={300} height={300} />
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 1</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>

            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={f} width={300} height={300}/>
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 2</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>
            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={a} width={300} height={300}/>
              </div>
              <h3 className='text-lg font-medium pt-4 pb-1'>Project 3</h3>
              <p className='py-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <h4 className='text-teal-600 pt-1'>Project specs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>React</p> 
              <p className='text-gray-800 dark:text-gray-400'>css</p> 
              <p className='text-gray-800 dark:text-gray-400'>figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>canva</p>
            </div>
          </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-6 text-gray-800 dark:text-gray-400'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse <span className='text-teal-600'>aliquet</span> sagittis est quis fermentum.
            Nullam accumsan <span className='text-teal-600'>hendrerit</span> malesuada. Maecenas tempus mi convallis nisl accumsan aliquet ut eget augue.
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basis-1/3 flex-1'>
              <Image src={Fisher} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' alt=''/>
              <div className='p-5'>
                <h3>Fisher</h3>
                <h4>School project: User experiences and interaction design</h4>
                <Link href="https://marvelapp.com/prototype/2dbi4f1g">Show prototype</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={SneakerHeadz} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              <div className='p-5'>
                <h3>SneakerHeadz</h3>
                <h4>School project: Web framework for Javascript - Group project</h4>
                <Link href="https://github.com/Vitoleander/SneakerHeadz">Show Github</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Sl} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              <div className='p-5'>
                <h3>SL new version</h3>
                <h4>School project: Frontend UX/UI - Group project</h4>
                <Link href="https://vxsm9q.axshare.com/#id=ci8ozr">Show prototype</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Login} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              <div className='p-5'>
                <h3>React Login Module</h3>
                <h4>React Login and Registration form with validation</h4>
                <Link href="https://github.com/Vitoleander/ReactLoginModul">Show Github</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Port} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              <div className='p-5'>
                <h3>Web development portfolio</h3>
                <h4>HTML, CSS portfolio with placeholders</h4>
                <Link href="https://github.com/Vitoleander/prof">Show Github</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Port2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              <div className='p-5'>
                <h3>Next.js Portfolio</h3>
                <h4>Written in Next.js and Tailwind CSS</h4>
                <Link href="https://github.com/Vitoleander/Next.js-Portfolio-with-Tailwind">Show Github</Link>
              </div>
            </div>

          </div>
        </section>

        <section>
          <footer className='p-10 flex justify-between'>
              <h1 className='text-xl dark:text-white'>Lorem ipsum © 2022</h1>
                  <ul className='flex items-center dark:text-teal-600'>
                      <li>
                        <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
                      </li>
                      <li className='pl-5'>
                        <AiFillHeart className='cursor-pointer text-2xl'/>
                      </li>
                  </ul>
          </footer>
        </section>
        
      </main>
    </div>
  )
}
