import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Link from 'next/link';

import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillHeart } from 'react-icons/ai';

import cv from '../public/cv.png';
import Fisher from '../public/Fisher.png';
import Sl from '../public/Sl.png';
import Login from '../public/login.png';
import Port from '../public/port.png';

import a from '../public/A.png';
import d from '../public/D.png';
import f from '../public/F.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Johannas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white'>
        
        <nav className='py-10 mb-12 flex justify-between sticky top-0 z-10'>
            <h1 className='text-teal-600 text-3xl font-bold dark:text-white'>Johanna Fogel</h1>
            <ul className='flex items-center'>
              <li className='flex justify-center text-center text-teal-600'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-4xl'/>
                Click here
                </li>

            </ul>
          </nav>

        <section className='min-h-screen relative'>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Welcome to my portfolio</h2>
            <h3 className='mt-5 text-2xl py-2 md:text-3xl'>Frontend developer and UX/UI.</h3>
            <p className='text-md py-5 leading-6 text-gray-800 md:text-xl mx-auto dark:text-gray-400'>
            Frontend student with a passion for UX/UI and design. Avalible for internship this spring.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-teal-700 '>
            <Link href="https://www.linkedin.com/in/johanna-fogel-47209670/"><AiFillLinkedin /></Link>
            <Link href="https://github.com/Vitoleander"><AiFillGithub /></Link>
            
          </div>

          <div className='relative mx-auto bg-gradient-to-t from-teal-700 w-90 h-90 rounded-full mt-20 flex justify-center lg:object-scale-down'>
            <Image src={cv} layout="fill" objectFit="cover" alt='cv image'/>
          </div>
        </section>

        <section className='text-center lg:mt-6'>
          <div>
            <h3 className='text-3xl pt-5'>My skills</h3>
            <p className='text-xl py-4 leading-6 text-gray-800 dark:text-gray-400'>
            I have always been 
            <span className='text-teal-600'>creative</span>
            , which you can see both in my professional life and in my free time. Soon I'll have a degree as 
            <span className='text-teal-600'>Frontend developer</span>
            , but over the years I've been taking courses in design and UX/UI. 
            My dream would be to work with 
            <span className='text-teal-600'>UX/UI</span> 
            and combine it with coding.
            </p>
          </div>

          <div className='lg:flex gap-10 text-center justify-center'>
            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={d} width={300} height={300} alt=''/>
              </div>
              <h3 className='py-1 text-xl'>This is some of the programs I use to design</h3>
              <h4 className='text-teal-600 pt-1 text-lg'>Programs:</h4>
              <p className='text-gray-800 dark:text-gray-400'>Adobe XD, Photoshop, InDesign</p> 
              <p className='text-gray-800 dark:text-gray-400'>Figma</p> 
              <p className='text-gray-800 dark:text-gray-400'>Uizard</p> 
              <p className='text-gray-800 dark:text-gray-400'>Axure</p>
            </div>

            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={f} width={300} height={300} alt=''/>
              </div>             
              <h3 className='py-1 text-xl'>This is some of the coding language I've learnt so far</h3>
              <h4 className='text-teal-600 pt-1 text-lg'>Code Language:</h4>
              <p className='text-gray-800 dark:text-gray-400'>HTML & CSS</p> 
              <p className='text-gray-800 dark:text-gray-400'>Javascript</p> 
              <p className='text-gray-800 dark:text-gray-400'>React & React Native</p> 
              <p className='text-gray-800 dark:text-gray-400'>Next.js</p>
            </div>
            <div className='shadow-lg p-10 rounded xl my-10 '>
              <div className='mx-auto flex justify-center'>
                <Image src={a} width={300} height={300} alt=''/>
              </div>
              <h3 className='py-1 text-xl'>Engaging myself in various type of creative sorts</h3>
              <h4 className='text-teal-600 pt-1 text-lg'>What I usually do:</h4>
              <p className='text-gray-800 dark:text-gray-400'>Painting</p> 
              <p className='text-gray-800 dark:text-gray-400'>Styling Homes & People</p> 
              <p className='text-gray-800 dark:text-gray-400'>Photography</p> 
              <p className='text-gray-800 dark:text-gray-400'>Flower, plants & gardening</p>
            </div>
          </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-5xl py-1 text-teal-600'>Portfolio</h3>
            <p className='text-xl mt-3 py-2 leading-6 text-gray-800 dark:text-gray-400'>
            Here are some of my recent designes and codes, This portfolio is a <span className='text-teal-600'>work-in-progress</span> and I'll be updating it as often as I can.
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basis-1/3 flex-1'>
              <Image src={Fisher} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' alt=''/>
              <div className='p-5'>
                <h4 className='mb-4 text-xl'>School project: User experiences and interaction design</h4>
                <Link className='bg-teal-600 text-white px-2 py-2 rounded-md cursor-pointer' href="https://marvelapp.com/prototype/2dbi4f1g">Show prototype</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Login} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' alt=''/>
              <div className='p-5'>
                <h4 className='mb-4 text-xl'>React Login and Registration form with validation</h4>
                <Link className='bg-teal-600 text-white px-2 py-2 rounded-md cursor-pointer' href="https://github.com/Vitoleander/ReactLoginModul">Show Github</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Sl} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' alt=''/>
              <div className='p-5'>
                <h4 className='mb-4 text-xl'>School project: Frontend UX/UI - Group project</h4>
                <Link className='bg-teal-600 text-white px-2 py-2 rounded-md cursor-pointer' href="https://vxsm9q.axshare.com/#id=ci8ozr">Show prototype</Link>
              </div>
            </div>

            <div className='basis-1/3 flex-1'>
              <Image src={Port} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' alt=''/>
              <div className='p-5'>
                <h4 className='mb-4 text-xl'>Web development portfolio - HTML, CSS portfolio with placeholders</h4>
                <Link className='bg-teal-600 text-white px-2 py-2 rounded-md cursor-pointer' href="https://github.com/Vitoleander/prof">Show Github</Link>
              </div>
            </div>
          </div>
        
        <div className='text-center mt-6 bg-teal-900 p-7'>
        <h3 className='text-5xl py-1 text-white'>Want to say hi?</h3>
        <h4 className='text-3xl text-white'> You can send me a mail at</h4>
        <h4 className='text-2xl text-white mt-2'>jfogel90@gmail.com</h4>
        </div>
        
        </section>

        <section>
          <footer className='p-10 flex justify-between'>
              <h1 className='text-xl dark:text-white'>Johanna Fogel © 2022</h1>
                  <ul className='flex items-center dark:text-teal-600'>
                      <li className='text-xl'>Page under construction</li>
                      <li className='pl-5'>
                        <AiFillHeart className='text-2xl mr-2'/>
                      </li>
                  </ul>
          </footer>
        </section>
        
      </main>
    </div>
  )
}
 

